/*
 * Bill Formatter
 * BEAS Bill Formatter
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pia.sample.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Extensible
 */
public class ExtensibleTest {
    private final Extensible model = new Extensible();

    /**
     * Model tests for Extensible
     */
    @Test
    public void testExtensible() {
        // TODO: test Extensible
    }

    /**
     * Test the property 'atType'
     */
    @Test
    public void atTypeTest() {
        // TODO: test atType
    }

    /**
     * Test the property 'atBaseType'
     */
    @Test
    public void atBaseTypeTest() {
        // TODO: test atBaseType
    }

    /**
     * Test the property 'atSchemaLocation'
     */
    @Test
    public void atSchemaLocationTest() {
        // TODO: test atSchemaLocation
    }

}
